# Generated by Django 5.1.1 on 2024-09-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunil', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Office_employee',
        ),
    ]
