# Generated by Django 5.1.1 on 2024-09-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr_code',
            name='id',
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='tag_number',
            field=models.UUIDField(default='7fc2', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
