# Generated by Django 5.1.1 on 2024-09-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_delete_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qr_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.UUIDField(default='9d', editable=False, unique=True)),
            ],
        ),
    ]
