# Generated by Django 5.1.1 on 2024-09-15 12:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_code',
            name='tag_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
