# Generated by Django 5.1.1 on 2024-09-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_alter_qr_code_tag_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_code',
            name='tag_number',
            field=models.UUIDField(default='3a1dbb26', editable=False, unique=True),
        ),
    ]
