# Generated by Django 5.1.1 on 2024-09-16 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_alter_qr_code_tag_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qr_code',
        ),
    ]
