# Generated by Django 5.1.1 on 2024-09-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0011_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_code',
            name='tag_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
