# Generated by Django 5.1.1 on 2024-09-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0012_alter_qr_code_tag_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_address', models.CharField(max_length=1000)),
                ('owner_name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
