# Generated by Django 5.1.1 on 2024-09-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0013_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='validity_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
