# Generated by Django 5.1.1 on 2024-09-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0014_validity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='validity_date',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
