# Generated by Django 5.1.1 on 2024-09-17 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0016_reward'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reward',
            new_name='Reward_item',
        ),
    ]
