# Generated by Django 5.1.1 on 2024-09-17 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0017_rename_reward_reward_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.qr_code')),
                ('reward_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.reward_item')),
            ],
        ),
    ]
